### ISSUE TITLE
Allowed maximum sentence length

### ISSUE THREAD

**Issue by interlark** [robertostling/eflomal#12]
Hi, what if I want to increase MAX_SENT_LEN from 0x400 to, let's say 0x1000. (changes max sentence's length in eflomal.c and eflomal.pyx). Would it work, what's your recommendation about increasing allowed maximum sentence length more than current limitation 1024 characters ?

**Comment by robertostling** [comment]
Technically it shouldn't be a problem, but I haven't evaluated alignment accuracy for very long sentences. The current length is 1024 **tokens**, not characters. So I guess you are rather talking about paragraphs or even whole texts. It will be interesting to hear if you are successful in aligning very long sentences accurately.

**Comment by interlark** [comment]
I've increased MAX_SENT_LEN up to 0x800 and even 0x1000 and it works great and I don't feel like accuracy goes down, but it takes a little bit longer than usually.
