### ISSUE TITLE
Failed to read token/ failed to read length

### ISSUE THREAD

**Issue by zparcheta** [robertostling/eflomal#15]
Hi,
I train a huge alignment model using +15M sentences and we get "failed to read token: Success". Also, on another occasion, I get the error "failed to read length: Success"
It does not occur with smaller data. Nither with small data with very long sentences. 
Could it be the memory problem? Maybe eflomal saves some temporal files which I have not taken into account?
Any idea?
regards and thanks in advance

**Comment by robertostling** [comment]
Hi, I think this indicates the temporary files have been truncated for some reason. The Python front-end converts the files to (ASCII-encoded) numeric temporary files sent to the C back-end.

It could be some issue with writing these large files the default temporary file directory on your system. You could test this hypothesis by passing dir='/some/safe/path' to the NamedTemporaryFile() calls in align.py.

Another possibility would be that for some reason the files aren't flushed properly before opened by the C back-end, although they should be (there is an fflush() call in eflomal.pyx::write_text()).

Robert

**Comment by zparcheta** [comment]
Hi @robertostling 
Thanks for your answer. the problem was the lack of space in /tmp
the problem is fixed
Thanks a lot
