### ISSUE TITLE
Make error on Ubuntu 20.04

### ISSUE THREAD

**Issue by carlosmruiz** [robertostling/eflomal#16]
Hi @robertostling , I'm somewhat new with this, but I just tried compiling eflomal into my Ubuntu machine in WSL 2 and got an error while running the make command and I cannot find any solution on Google.

Here's the output:

cc -Ofast -march=native -Wall --std=gnu99 -Wno-unused-function -g -fopenmp -c eflomal.c
cc1: error: bad value (‘tigerlake’) for ‘-march=’ switch
cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native
cc1: error: bad value (‘tigerlake’) for ‘-mtune=’ switch
cc1: note: valid arguments to ‘-mtune=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm intel x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 generic native
make: *** [Makefile:10: eflomal.o] Error 1

Any idea why?

Any help would greatly be appreciated. I just can't get around this issue.

**Comment by robertostling** [comment]
@carlosmruiz -- that looks weird, since a valid -march=native argument is passed. I don't know why tigerlake is inserted there instead. Since I can't reproduce the error here it's difficult for me to debug, but if you have multiple C compilers you could try changing the value of CC until you find one that works. Does your C compiler setup work for any program, or is it just eflomal that fails? As you can see in the Makefile, it's really very simple and not much that should go wrong.

**Comment by carlosmruiz** [comment]
@robertostling I'm no expert at this, I tried what you mentioned but I was not sure if I was doing it correctly. But after trying and researching endlessly, I found out that installing a higher version of gcc and g++ worked.

sudo apt install gcc-10 g++-10

make CC=gcc-10 CPP=g++-10 CXX=g++-10 LD=g++-10

That worked for me and then I tried installing eflomal again and everything worked perfectly, I could run the make command as normal.

For other people that may experience this issue, in Ubuntu 20.04 LTS everything works fine after running those two commands. In Ubuntu, unfortunately, it seems you need to run those two commands for the compiler to work. In Ubuntu 18.04, I haven't ran into this problem, so you wouldn't need to do anything.

**Comment by robertostling** [comment]
@carlosmruiz great to hear it worked out for you after upgrading!
