### ISSUE TITLE
Input data format

### ISSUE THREAD

**Issue by PhilBau** [robertostling/eflomal#3]
Hi Robert,
thank you for your help and the nice development you made with your team, I want to give Eflomal a try.
But can you add some indications about the input data format supported by Eflomal (or tell me where it is written)?
I have formatted my data like in the "3rdparty/data/" folder and just learned (see https://github.com/robertostling/eflomal/issues/2#issuecomment-320925112) it wasn't necessary :-) .
Best, Philippe

**Comment by robertostling** [comment]
Thanks for pointing this out, I have clarified this (and also removed the `3rdparty/data` files) in 55dfe87
