### ISSUE TITLE
Compile error on OSX Mojave

### ISSUE THREAD

**Issue by andremarco** [robertostling/eflomal#9]
Trying to execute the _make_ command I get the following error:
`clang: error: unsupported option '-fopenmp'`

I tried to install _gcc_ via brew using:
`brew install cmake gcc`
but it doesn't change anything.
How to fix it?

**Comment by andremarco** [comment]
Solved using an update version of gcc that support `'-fopenmp'`.
Sorry for noise.

**Comment by ymoslem** [comment]
1- installing the right version of gcc
2- referring to it

The second step can be with something like:
`export CC=/usr/local/bin/gcc`

In my case, it was gcc-9

Reference ([link](https://stackoverflow.com/questions/36211018/clang-error-errorunsupported-option-fopenmp-on-mac-osx-el-capitan-buildin))
